### ISSUE TITLE
[Feature request] Make the subs allowed to be async

### ISSUE THREAD

**Issue by akarelas** [dmanto/Mojolicious-Plugin-Cron#11]
Could you make the sub callbacks allowed to be async functions? (see Future::AsyncAwait)

This would allow subs that have a long duration (such as massive cleanup subs) to be called by cron, without interrupting the real-time nature of the Mojolicious framework.

I could write a PR for you if you want. It's only a few lines of code, I believe, it's not hard to do.

**Comment by dmanto** [comment]
Ok, please prepare a PR and I'll take a look at it.

Also note that the current implementation does allow non-blocking operations (through callbacks)

**Comment by akarelas** [comment]
Which callback is that? Is it documented? I can't find it in the documentation

**Comment by akarelas** [comment]
You're right.
My idea is not really needed, is it?
You already can use async subs.

**Comment by dmanto** [comment]
Probably not, but I just realized after your last answer :)

Mojo framework evolved from callbacks only to recommend promises and finally the use of async / await.

As a first step we could upgrade the plugin to have a "promises like" solution, converting it to a "thennable" plugin, like 

```
plugin Chron_p ('* * ...')->then(sub {})...

``` 

But I don't see the real benefit here, as probably many of the advantages promises allow, like ->race, or ->all, doesn't really make sense to me for crons.

For async / await is probably worst. I imagine async / await naturally fitting on subs that only run one time after called.
Also note that you normally establish all the crons  that you may need at the begining of the app, before calling the start method. So if you 'await' there for some cron in the future, the hole program will wait, despite you are not blocking the ioloop, but still, nothing will happen until the cron fires the first time. 

But as you said, inside the subs called by Cron you can use wathever you need (as long you don't block the ioloop).

For long processes like the ones you mentioned in the issue, what I do is trigger a Minion job. That will not block your ioloop.

**Comment by akarelas** [comment]
I should close this issue, right?

**Comment by akarelas** [comment]
I should close this issue, right?
