### ISSUE TITLE
Possible doc issue?

### ISSUE THREAD

**Issue by haukex** [dmanto/Mojolicious-Plugin-Cron#8]
Hi, the extended syntax is documented as being both

    plugin Cron => ( sched1 => { ...

and

    plugin Cron => { key1 => ...

It's unclear to me if both work?

*Edit:* Also, I think `'*/10 15 * * *', # every 10 minutes starting at minute 15, every hour` isn't correct, is it?

**Comment by dmanto** [comment]
Hi,

For the first question, yes, both work (i.e it accepts a list or a hashref).

I guess it's a little confusing, but I think I saw several Mojo Plugins using both conventions, will check that and let you know.

And for the second question, no, it does not look correct :(

Crontab string should have been '15-59/10 * * * *' for that comment

**Comment by haukex** [comment]
Ok, thanks for the information!

**Comment by dmanto** [comment]
Several doc fixes in v0.028, please check them

**Comment by haukex** [comment]
Thank you!
